var GameEnvironment=function(){var d={idle:new $.gQ.Animation({imageURL:"images/CatGunIdle.png",numberOfFrame:8,delta:97,rate:100,type:$.gQ.ANIMATION_HORIZONTAL}),walkRight:new $.gQ.Animation({imageURL:"images/CatGunWalkRight.png",numberOfFrame:8,delta:96,rate:100,type:$.gQ.ANIMATION_HORIZONTAL}),walkLeft:new $.gQ.Animation({imageURL:"images/CatGunWalkLeft.png",numberOfFrame:8,delta:96,rate:100,type:$.gQ.ANIMATION_HORIZONTAL})},c={fireRight:new $.gQ.Animation({imageURL:"images/player_missile_right.png",
numberOfFrame:6,delta:10,rate:90,type:$.gQ.ANIMATION_VERTICAL}),fireLeft:new $.gQ.Animation({imageURL:"images/player_missile_left.png",numberOfFrame:6,delta:10,rate:90,type:$.gQ.ANIMATION_VERTICAL})},a=function(){$("#startbutton").click(function(){$.playground().startGame(function(){$("#welcomeScreen").fadeTo(1E3,0,function(){$(this).remove()})})})};return{initGame:function(){Playground.init(500,700);Playground.setupScenery("images/grass.png","images/plants.png","images/stars.png");Player.init(48,
75,d,c);Playground.setupPlayer();a()},getHeight:function(){return 500},getWidth:function(){return 700},getRefreshRate:function(){return 30}}}(),Playground=function(){var d,c=500,a=700;return{init:function(b,d){$("#playground").playground({height:b,width:d,keyTracker:!0});c=b;a=d},setupScenery:function(b,f,e){e=new $.gQ.Animation({imageURL:e});f=new $.gQ.Animation({imageURL:f});b=new $.gQ.Animation({imageURL:b});d=$.playground().addGroup("scenery",{width:a,height:c}).addSprite("background1",{animation:e,
width:a,height:c}).addSprite("background2",{animation:e,width:a,height:c,posx:a}).addSprite("middleground1",{animation:f,width:a,height:c}).addSprite("middleground2",{animation:f,width:a,height:c,posx:a}).addSprite("foreground1",{animation:b,width:a,height:c}).addSprite("foreground2",{animation:b,width:a,height:c,posx:a}).end()},setupPlayer:function(){d.addGroup("actors",{width:a,height:c});var b={posx:a/2,posy:c/2,width:Player.getWidth(),height:Player.getHeight()},f={animation:Player.getIdleAnimation(),
posx:0,posy:0,width:Player.getWidth(),height:Player.getHeight()},e={posx:0,posy:0,width:Player.getWidth(),height:Player.getHeight()},g={posx:0,posy:0,width:Player.getWidth(),height:Player.getHeight()};d=d.addGroup("player",b).addSprite(Player.getIdleSprite(),f).addSprite(Player.getWalkRightSprite,e).addSprite(Player.getWalkLeftSprite,g).end();d.addGroup("playerWeaponLayer",{width:a,height:c}).end()},scrollScenery:function(){var b=(parseInt($("#background1").x())-1-a)%(-2*a)+a;$("#background1").x(b);
b=(parseInt($("#background2").x())-1-a)%(-2*a)+a;$("#background2").x(b);b=(parseInt($("#middleground1").x())-3-a)%(-2*a)+a;$("#middleground1").x(b);b=(parseInt($("#middleground2").x())-3-a)%(-2*a)+a;$("#middleground2").x(b);b=(parseInt($("#foreground1").x())-4-a)%(-2*a)+a;$("#foreground1").x(b);b=(parseInt($("#foreground2").x())-4-a)%(-2*a)+a;$("#foreground2").x(b)},topOfMoveableArea:function(){return 270},scrollingPoint:function(){return 270},getWeaponLayer:function(){return"playerWeaponLayer"}}}(),
Player=function(){var d,c,a,b,f,e,g=!1,h=!1,k=function(){return $("#player").x()>Playground.scrollingPoint()&&!g};return{init:function(l,g,h,k){d=l;c=g;a=h.idle;b=h.walkRight;f=h.walkLeft;PlayerWeapon.init(k);e=PlayerWeapon},getHeight:function(){return d},getWidth:function(){return c},getWeapon:function(){return e},getIdleAnimation:function(){return a},getIdleSprite:function(){return"playerIdle"},getWalkRightSprite:function(){return"playerWalkRight"},getWalkLeftSprite:function(){return"playerWalkLeft"},
animateIdle:function(){$("#playerWalkRight").setAnimation();$("#playerWalkLeft").setAnimation();$("#playerIdle").setAnimation(a);g=!0;h=!1},animateWalkingRight:function(){$("#playerIdle").setAnimation();$("#playerWalkLeft").setAnimation();$("#playerWalkRight").setAnimation(b);h=g=!1},animateWalkingLeft:function(){$("#playerIdle").setAnimation();$("#playerWalkRight").setAnimation();$("#playerWalkLeft").setAnimation(f);g=!1;h=!0},moveRight:function(){var a=$("#player").x()+(k()?1:4);a<GameEnvironment.getWidth()-
30&&$("#player").x(a)},moveUp:function(){var a=$("#player").y()-2;0<a&&a>=Playground.topOfMoveableArea()&&$("#player").y(a)},moveLeft:function(){var a=$("#player").x()-4;0<a&&$("#player").x(a)},moveDown:function(){var a=$("#player").y()+2;a<GameEnvironment.getHeight()-30&&$("#player").y(a)},isIdle:function(){return g},isAdvancing:k,xPosition:function(){return $("#player").x()},yPosition:function(){return $("#player").y()},setStartingPosition:function(){$("#player").x(90);$("#player").y(343)},fireWeapon:function(){e.fire()},
isFacingLeft:function(){return h}}}(),PlayerWeapon=function(){var d,c,a;return{init:function(b){d=b.fireLeft;c=b.fireRight;a="#"+Playground.getWeaponLayer()},fire:function(){var b="playerAttack_"+Math.ceil(1E3*Math.random());Player.isFacingLeft()?($(a).addSprite(b,{animation:d,posx:Player.xPosition()-20,posy:Player.yPosition()+22,width:36,height:10}),$("#"+b).addClass("attackLeft")):($(a).addSprite(b,{animation:c,posx:Player.xPosition()+70,posy:Player.yPosition()+22,width:36,height:10}),$("#"+b).addClass("attackRight"))},
getAttackLeftName:function(){return"attackLeft"},getAttackRightName:function(){return"attackRight"}}}();
$(function(){GameEnvironment.initGame();KeyBindings.registerPlayerActionAnimations();Player.setStartingPosition();var d="."+Player.getWeapon().getAttackLeftName(),c="."+Player.getWeapon().getAttackRightName();$.playground().registerCallback(function(){KeyBindings.handlePlayerMovement();$(c).each(function(){$(this).x()>GameEnvironment.getWidth()?$(this).remove():$(this).x(10,!0)});$(d).each(function(){0>$(this).x()?$(this).remove():$(this).x(-10,!0)})},GameEnvironment.getRefreshRate())});
var KeyBindings=function(){var d=!1,c=!1,a=!1,b=!1,f=!1,e=0;return{handlePlayerMovement:function(){d||(c||a||b)||Player.isIdle()||Player.animateIdle();Player.isAdvancing()&&Playground.scrollScenery();jQuery.gameQuery.keyTracker[65]&&Player.moveLeft();jQuery.gameQuery.keyTracker[68]&&Player.moveRight();jQuery.gameQuery.keyTracker[87]&&Player.moveUp();jQuery.gameQuery.keyTracker[83]&&Player.moveDown()},registerPlayerActionAnimations:function(){$(document).keydown(function(g){switch(g.keyCode){case 65:if(a)break;
a=!0;Player.animateWalkingLeft();break;case 87:if(c)break;c=!0;Player.animateWalkingRight();break;case 68:if(b)break;b=!0;Player.animateWalkingRight();break;case 83:if(d)break;d=!0;Player.animateWalkingRight();break;case 75:f?(e++,0==e%5&&Player.fireWeapon()):(Player.fireWeapon(),f=!0)}});$(document).keyup(function(g){switch(g.keyCode){case 65:a=!1;break;case 87:c=!1;break;case 68:b=!1;break;case 83:d=!1;break;case 75:e=0,f=!1}})}}}();
